### ISSUE TITLE
[bug] fix categories and tags URL

### ISSUE THREAD

**Issue by rootsongjc** [sofastack/sofastack.tech#163]
Site linting errors when generating the preview site.
```
- ./public/categories/sqlflow/page/1/index.html
  *  External link https://www.sofastack.tech/categories/sqlflow/ failed: 404 No error
- ./public/tags/sqlflow/page/1/index.html
  *  External link https://www.sofastack.tech/tags/sqlflow/ failed: 404 No error
```
Replace categories and tags links with a relative path.

**Comment by rootsongjc** [comment]
fixed

**Comment by Deturium** [comment]
The page only contain a redirect meta  `<meta http-equiv="refresh" content="0; url=https://www.sofastack.tech/tags/:YOUR_TAG" />` 

This is automatically generated by hugo，I can't find any way to override this template yet.

Maybe we can to override the baseURL in config.toml when build a preview site ? 
Use  `hugo --baseURL=http://PREVIEW_DOMAIN.xxx`

**Comment by rootsongjc** [comment]
Linting error solved. Refer to the preview sites https://sofastack-preview.netlify.com/categories/seata/
