### ISSUE TITLE
correct wrong chapter references of jraft-user-guide(zh)

### ISSUE THREAD

**Issue by xiangwangcheng** [sofastack/sofastack.tech#379]
There are a few wrong chapter references and some other uninfluenced sentences in the Chinese jraft-user-guide. These need to be corrected to avoid confusion.
such as:
![image](https://user-images.githubusercontent.com/8049014/71614760-a04c8d80-2be8-11ea-8cfb-faf63241d9d7.png)

![image](https://user-images.githubusercontent.com/8049014/71614834-fc171680-2be8-11ea-92cd-7b0011631b6d.png)

and so on.

**Comment by xiangwangcheng** [comment]
Please let me know if someone else is already working on this.

**Comment by rootsongjc** [comment]
@fengjiachun can you have a look this issue?
