### ISSUE TITLE
文档勘误

### ISSUE THREAD

**Issue by GuldanChen** [sofastack/sofastack.tech#568]
链接：https://www.sofastack.tech/blog/sofastack-modular-isolation/
问题描述：文档末尾在举例系统拆分时新服务发布的例子中出现重复。
![image](https://user-images.githubusercontent.com/26451311/94168883-af831200-fec0-11ea-9f8e-3613093cb2cd.png)

**Comment by seeflood** [comment]
没有重复哈，一个是 ref="sampleBean" 一个是id=...
