### ISSUE TITLE
[doc] Typo in lettercase

### ISSUE THREAD

**Issue by arjenzhou** [sofastack/sofastack.tech#570]
There is a typo in `加入 SOFAStack GItHub 组织，成为 SOFAStack 开源社区的一员。` which should be lowercase `i` not `I`
https://github.com/sofastack/sofastack.tech/blob/master/content/zh/community/_index.md#contributor

I am glad to fix this.

**Comment by rootsongjc** [comment]
Sure, please go ahead.
