### ISSUE TITLE
[bug] disable cover images for categories page

### ISSUE THREAD

**Issue by rootsongjc** [sofastack/sofastack.tech#81]
Linting site error:
```
./public/categories/index.html

- image has no src or srcset attribute (line 181)
- image has no src or srcset attribute (line 200)
- image has no src or srcset attribute (line 352)
- image has no src or srcset attribute (line 333)
- image has no src or srcset attribute (line 314)
- image has no src or srcset attribute (line 219)
- image has no src or srcset attribute (line 238)
- image has no src or srcset attribute (line 295)
- image has no src or srcset attribute (line 257)
- image has no src or srcset attribute (line 276)
```
Disable cover images for https://www.sofastack.tech/categories/ will solve this problem.

**Comment by Deturium** [comment]
We need to add a new layout template `layouts/_default/terms.html` for this list page and `/tags`.

**Comment by rootsongjc** [comment]
Temporary solution: disable the taxonomy terms.

**Comment by rootsongjc** [comment]
Taxonomy pages recovered https://www.sofastack.tech/tags/ @Deturium

**Comment by rootsongjc** [comment]
Deleted index.html and index.xml files on `tags` and `categories` directories.

**Comment by rootsongjc** [comment]
Close this issue. New feature request: creating categories and tags list pages.
