### ISSUE TITLE
[doc] SOFAMesh官方文档错误

### ISSUE THREAD

**Issue by CodingSinger** [sofastack/sofastack.tech#93]
官方文档下
https://www.sofastack.tech/projects/sofa-mesh/pilot-setup-zookeeper-quick-start-docker/

![image](https://user-images.githubusercontent.com/18573670/61503655-3316b880-aa0b-11e9-8ca9-996a8f7b26ab.png)
在最新release的sofamesh下并没发现该文件

**Comment by rootsongjc** [comment]
@sofastack/sofa-mesh-members

**Comment by JamazRuan** [comment]
@CodingSinger The directory "install/zookeeper" is no longer generated, we will modify the doc for deployment as soon.

**Comment by JamazRuan** [comment]
@CodingSinger https://deploy-preview-142--sofastack-preview.netlify.com/projects/sofa-mesh/sofa-mesh-setup/

**Comment by rootsongjc** [comment]
@CodingSinger Is your problem solved? Can I close the issue?

**Comment by rootsongjc** [comment]
No response, close the issue.
